version: "3.9"
services:
  backend:
    container_name: superdeepagent_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - CUDA_VISIBLE_DEVICES=all
      - ENABLE_PLUGINS=true
      - PLUGINS_DIR=/app/plugins
    volumes:
      - .:/app
      - ./user_plugins:/app/plugins:ro
      - /app/__pycache__
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
  chroma_data:
