apiVersion: apps/v1
kind: Deployment
metadata:
  name: superdeepagent-backend
  labels:
    app: superdeepagent
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superdeepagent
      component: backend
  template:
    metadata:
      labels:
        app: superdeepagent
        component: backend
    spec:
      containers:
      - name: backend
        image: ${REGISTRY}/superdeepagent-backend:${TAG}
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: ENV
          value: "production"
        - name: CUDA_VISIBLE_DEVICES
          value: "all"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: superdeepagent-config
      nodeSelector:
        accelerator: nvidia-gpu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superdeepagent-frontend
  labels:
    app: superdeepagent
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superdeepagent
      component: frontend
  template:
    metadata:
      labels:
        app: superdeepagent
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ${REGISTRY}/superdeepagent-frontend:${TAG}
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.superdeepagent.com/api"
