apiVersion: v1
kind: Service
metadata:
  name: superdeepagent-backend
  labels:
    app: superdeepagent
    component: backend
spec:
  selector:
    app: superdeepagent
    component: backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: superdeepagent-frontend
  labels:
    app: superdeepagent
    component: frontend
spec:
  selector:
    app: superdeepagent
    component: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superdeepagent-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: api.superdeepagent.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: superdeepagent-backend
            port:
              number: 80
  - host: superdeepagent.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: superdeepagent-frontend
            port:
              number: 80
  tls:
  - hosts:
    - api.superdeepagent.com
    - superdeepagent.com
    secretName: superdeepagent-tls
